//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberIntrest
    {
        public short MemberIntrestId { get; set; }
        public int MemberId { get; set; }
        public short MemberCatagoryId { get; set; }
        public Nullable<short> MemberSubCatagoryId { get; set; }
        public Nullable<double> MemberIntrestNoOfYears { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MemberCatagory MemberCatagory { get; set; }
        public virtual MemberSubCatagory MemberSubCatagory { get; set; }
    }
}
