//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEducation
    {
        public short MemberEducationId { get; set; }
        public int MemberId { get; set; }
        public string MemberDegreeName { get; set; }
        public string MemberDegreeInstitue { get; set; }
        public string MemberDegreePercentage { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
