//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMentor
    {
        public short MemberMentorId { get; set; }
        public int MemberId_Mentor { get; set; }
        public int MemberId_Mentore { get; set; }
        public Nullable<System.DateTime> MentoreFollowRequestDateTime { get; set; }
        public Nullable<System.DateTime> MentorFollowApproveDateTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
