//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentorEF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MentorEntities : DbContext
    {
        public MentorEntities()
            : base("name=MentorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberCatagory> MemberCatagories { get; set; }
        public virtual DbSet<MemberEducation> MemberEducations { get; set; }
        public virtual DbSet<MemberExperiance> MemberExperiances { get; set; }
        public virtual DbSet<MemberIntrest> MemberIntrests { get; set; }
        public virtual DbSet<MemberMentor> MemberMentors { get; set; }
        public virtual DbSet<MemberRate> MemberRates { get; set; }
        public virtual DbSet<MemberSubCatagory> MemberSubCatagories { get; set; }
    }
}
